name: Update GitHub Secrets from Vault

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-secrets:
    runs-on: [self-hosted, Windows, x64]

    steps:
    
    - name: Install jq
      run: |
        # Download jq.exe
        Invoke-WebRequest -Uri https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe -OutFile $env:USERPROFILE\jq.exe
        # Add the directory to PATH for the current session
        [Environment]::SetEnvironmentVariable("PATH", "$env:USERPROFILE;$env:PATH", [System.EnvironmentVariableTarget]::Process)
        # Verify installation
        jq --version


    - name: Verify Vault Token
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      run: |
        vault.exe token lookup -format=json | jq '.data'
  
    - name: Cache Vault Data Hash
      id: cache_hash
      uses: actions/cache@v3
      with:
        path: .vault_data_hash
        key: vault-data-hash-${{ hashFiles('.vault_data_hash') }}
  
    - name: Check Vault for Changes
      id: check_vault
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      run: |
        # For KV Version 1
        $NEW_HASH = vault.exe kv get -format=json secret/myapp | jq -r '.data' | ConvertTo-Json
        if (Test-Path .vault_data_hash) {
          $OLD_HASH = Get-Content .vault_data_hash
        } else {
          $OLD_HASH = ""
        }
        if ($NEW_HASH -ne $OLD_HASH) {
          Write-Host "Vault data has changed."
          $NEW_HASH | Out-File .vault_data_hash
          echo "has_changed=true" | Out-File $env:GITHUB_OUTPUT -Append
        } else {
          Write-Host "No changes in Vault data."
          echo "has_changed=false" | Out-File $env:GITHUB_OUTPUT -Append
        }
  
    - name: Fetch Secrets from Vault
      id: fetch-secrets
      if: steps.check_vault.outputs.has_changed == 'true'
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      run: |
        $ErrorActionPreference = 'Stop'
        $SECRET_PATHS = @("secret/myapp")
        $SECRETS_JSON = @{}
        
        foreach ($SECRET_PATH in $SECRET_PATHS) {
            Write-Host "Fetching secrets from: $SECRET_PATH"
            try {
                $SECRET_DATA = vault.exe kv get -format=json $SECRET_PATH | jq -r '.data' | ConvertFrom-Json
                Write-Host "Fetched data: $($SECRET_DATA | ConvertTo-Json -Depth 10)"
            } catch {
                Write-Error "Failed to fetch secrets from Vault. Error: $_"
                exit 1
            }
    
            # Ensure $SECRET_DATA is a hashtable
            if ($SECRET_DATA -is [hashtable]) {
                Write-Host "Secret data is a hashtable."
            } else {
                Write-Error "Secret data is not a hashtable. Actual type: $($SECRET_DATA.GetType())"
                exit 1
            }
            
            # Merge $SECRET_DATA into $SECRETS_JSON
            foreach ($key in $SECRET_DATA.Keys) {
                $SECRETS_JSON[$key] = $SECRET_DATA[$key]
            }
        }
        
        # Output secrets as JSON
        $SECRETS_JSON | ConvertTo-Json -Depth 100 | Out-File -FilePath secrets.json
        Write-Host "Combined secrets:"
        Get-Content -Path secrets.json | Write-Host
    
    - name: Update GitHub Secrets
      if: steps.check_vault.outputs.has_changed == 'true'
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        $ErrorActionPreference = 'Stop'
        
        # Output starting message
        Write-Host "Starting the 'Update GitHub Secrets' step."
        
        # Parse repository information
        $REPO = $env:GITHUB_REPOSITORY -split "/"
        $OWNER = $REPO[0]
        $REPO_NAME = $REPO[1]
        Write-Host "Repository Owner: $OWNER"
        Write-Host "Repository Name: $REPO_NAME"
        
        # Read secrets from file
        if (Test-Path -Path secrets.json) {
            $SECRETS_JSON = Get-Content -Path secrets.json | ConvertFrom-Json
            Write-Host "Contents of secrets.json:"
            Get-Content -Path secrets.json | Write-Host
        } else {
            Write-Error "secrets.json file not found."
            exit 1
        }
        
        if ($SECRETS_JSON -eq $null) {
            Write-Error "No secrets found in secrets.json."
            exit 1
        }
        
        $secretNames = $SECRETS_JSON.PSObject.Properties.Name
        Write-Host "Secrets to update: $($secretNames -join ', ')"
        
        foreach ($secret in $SECRETS_JSON.PSObject.Properties) {
          $secret_name = $secret.Name
          $secret_value = $secret.Value
        
          Write-Host "Updating secret: $secret_name"
    
          # Get the public key for the repository
          try {
            $response = Invoke-RestMethod -Headers @{ Authorization = "token $($env:GH_PAT)" } `
              -Uri "https://api.github.com/repos/$OWNER/$REPO_NAME/actions/secrets/public-key" `
              -UseBasicParsing
    
            $key_id = $response.key_id
            $public_key = $response.key
    
            Write-Host "Retrieved public key for repository."
          }
          catch {
            Write-Error "Failed to get public key. Error: $_"
            exit 1
          }
    
          # Encryption process
          try {
            $publicKeyBytes = [Convert]::FromBase64String($public_key)
            $rsa = [System.Security.Cryptography.RSACryptoServiceProvider]::Create()
            $rsa.ImportSubjectPublicKeyInfo($publicKeyBytes, [ref]0)
            $secretBytes = [System.Text.Encoding]::UTF8.GetBytes($secret_value)
            $encryptedBytes = $rsa.Encrypt($secretBytes, [System.Security.Cryptography.RSAEncryptionPadding]::OaepSHA256)
            $encrypted_value = [Convert]::ToBase64String($encryptedBytes)
    
            Write-Host "Secret '$secret_name' encrypted successfully."
          }
          catch {
            Write-Error "Failed to encrypt secret '$secret_name'. Error: $_"
            continue
          }
    
          # Prepare the body for the API request
          $body = @{
            encrypted_value = $encrypted_value
            key_id = $key_id
          } | ConvertTo-Json
    
          # Update the secret
          try {
            $updateResponse = Invoke-RestMethod -Method Put -Headers @{ Authorization = "token $($env:GH_PAT)" } `
              -Uri "https://api.github.com/repos/$OWNER/$REPO_NAME/actions/secrets/$secret_name" `
              -ContentType "application/json" -Body $body -UseBasicParsing
    
            Write-Host "Secret '$secret_name' updated successfully."
          }
          catch {
            Write-Error "Failed to update secret '$secret_name'. Error: $_"
          }
        }
